# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.srcs/sources_1/ip/fir_compiler_4/fir_compiler_4.xci
# IP: The module: 'fir_compiler_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.gen/sources_1/ip/fir_compiler_4/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.gen/sources_1/ip/fir_compiler_4/fir_compiler_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.srcs/sources_1/ip/fir_compiler_4/fir_compiler_4.xci
# IP: The module: 'fir_compiler_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.gen/sources_1/ip/fir_compiler_4/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.gen/sources_1/ip/fir_compiler_4/fir_compiler_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
