# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.srcs/sources_1/ip/dds_compiler_2/dds_compiler_2.xci
# IP: The module: 'dds_compiler_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.gen/sources_1/ip/dds_compiler_2/dds_compiler_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.srcs/sources_1/ip/dds_compiler_2/dds_compiler_2.xci
# IP: The module: 'dds_compiler_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/NTT/WorkingDirectory/09.23/Vivado/UniDec/UniDec.gen/sources_1/ip/dds_compiler_2/dds_compiler_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
